In [3]:
# Revisions 
import numpy as np 

In [7]:
a = np.array([1,2,3,4])
b = np.array([(2,3,4,6),(5,4,5,6)] , dtype=float)

In [8]:
a,b

(array([1, 2, 3, 4]),
 array([[2., 3., 4., 6.],
        [5., 4., 5., 6.]]))

In [11]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
d = np.ones((2,3,4) , dtype=np.int16)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
D = np.arange(4,2,3)
D

array([], dtype=int32)

In [16]:
np.linspace(2,3,9,2)

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

In [18]:
a.shape
len(a)

4

In [26]:
a.size
a.ndim
a.dtype
a.astype(float)

array([1., 2., 3., 4.])

In [27]:
a

array([1, 2, 3, 4])

In [28]:
import pandas as pd 

In [30]:
df = pd.DataFrame(
    {"a" : [4, 5, 6],
     "b" : [7, 8, 9],
     "c" : [10, 11, 12]
    },
     index = [1, 2, 3]
    )


In [31]:
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [33]:
df = pd.DataFrame(
                 [[4, 7, 10],[5, 8, 11],[6, 9, 12]],
                 index=[1, 2, 3],
                 columns=['a', 'b', 'c']
                 )


In [34]:
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [36]:
df = (pd.melt(df).rename(columns={'variable':'var','value':'val'}).query('val >= 200'))
df

Empty DataFrame
Columns: [var, val]
Index: []

In [ ]:
Data = pd.read_csv(../Tuttoriel et cours/TuttoTweets.csv)