In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [4]:
# Charger un jeu de données

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.6490754 , -0.00718692,  0.4091198 , -0.15649788, -0.47734442,
         0.24657813,  0.29139093, -0.12618566, -0.2506702 , -0.4064103 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.17668797, 0.09166338, 0.13899386, 0.07894979, 0.0572808 ,
        0.11814209, 0.12355678, 0.08137957, 0.07185425, 0.06149154]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.135867

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2945 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1430 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1091 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0874 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0750 - accuracy: 0.9770


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0768 - accuracy: 0.9754 - 833ms/epoch - 3ms/step


[0.07683351635932922, 0.9753999710083008]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.14785223e-07, 2.21858905e-08, 1.29699583e-05, 3.52862582e-04,
        2.50122514e-12, 6.39628297e-08, 2.10164373e-12, 9.99630570e-01,
        1.06459474e-07, 3.24151256e-06],
       [1.71947612e-09, 4.28995554e-06, 9.99974847e-01, 1.28448837e-05,
        2.20950291e-16, 8.04341471e-06, 4.22350421e-09, 1.00121528e-15,
        4.55488554e-08, 6.66847382e-13],
       [1.04018352e-06, 9.99292731e-01, 1.93734188e-04, 8.14850591e-06,
        4.23436322e-05, 9.03482851e-06, 3.26985974e-05, 3.25739325e-04,
        9.33950651e-05, 1.05139350e-06],
       [9.99859452e-01, 5.28192545e-10, 1.33459660e-04, 4.78498769e-08,
        1.57206053e-08, 6.49403376e-07, 4.06420941e-06, 1.93174151e-06,
        3.33676281e-10, 3.17478538e-07],
       [4.43398312e-06, 8.67862560e-10, 2.23274469e-06, 1.00574880e-07,
        9.95602369e-01, 7.87533949e-08, 2.47918138e-07, 5.44201059e-04,
        8.72804947e-07, 3.84546025e-03]], dtype=float32)>